### ISSUE TITLE
Remove old logic for available filter. Read data from json files instead

### ISSUE THREAD

**Issue by nikolaydymura** [nikolaydymura/native_filters#10]

**Comment by kavantrivedi** [comment]
hey  @nikolaydymura,
I wanted to use this plugin for video filters in a project but does this support both platforms?

**Comment by nikolaydymura** [comment]
@kavantrivedi yes you can use it for videos too. The package supports passing video files as well as the photo file. If something doesn't work we will be glad to help you.

**Comment by kavantrivedi** [comment]
@nikolaydymura  
Thank you for the quick response, I have to open a camera with the applied filter on it, any idea how we can do that?

**Comment by nikolaydymura** [comment]
@kavantrivedi for now it's only available in native solutions like CIFilter for ios or some GPUVideo for Android. We plan to have this functionality in flutter soon, but couldn't predict a time

**Comment by kavantrivedi** [comment]
@nikolaydymura  
Thank you for the suggestions
