### ISSUE TITLE
compatible versions

### ISSUE THREAD

**Issue by binvb** [nikolaydymura/native_filters#31]
thanks for this plugin.   
but i found something wrong in my project: 
CocoaPods could not find compatible versions for pod "native_filters":

i saw your flutter sdk version range(sdk: ">=2.18.2 <3.0.0"), but i can't find it at document: https://docs.flutter.dev/development/tools/sdk/releases

**Comment by nikolaydymura** [comment]
@binvb We developed new solutions for image/video filtering, you can try them.

https://pub.dev/packages/flutter_core_image_filters
https://pub.dev/packages/flutter_image_filters
https://pub.dev/packages/flutter_gpu_video_filters

**Comment by binvb** [comment]
thank you
